# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 09:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_user',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 30, 9, 22, 34, 629112, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='active_user',
            name='user',
            field=models.CharField(max_length=10, verbose_name='用户名'),
        ),
    ]
