# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0002_auto_20161229_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='active_user',
            old_name='actice_str',
            new_name='active_str',
        ),
        migrations.AlterField(
            model_name='active_user',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 30, 9, 33, 1, 334073, tzinfo=utc)),
        ),
    ]
