# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 09:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0003_auto_20161229_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='active_user',
            options={'verbose_name': '用户激活', 'verbose_name_plural': '用户激活'},
        ),
        migrations.AlterField(
            model_name='active_user',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 30, 9, 46, 15, 639631, tzinfo=utc)),
        ),
    ]
