# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 07:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0004_auto_20161229_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_user',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 21, 7, 41, 42, 348342, tzinfo=utc)),
        ),
    ]
