# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_auto_20161121_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='name',
            new_name='names',
        ),
    ]
