# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20161122_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (-1, '关闭')], verbose_name='状态'),
        ),
    ]
